# Generated by Django 3.2.8 on 2021-11-24 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='')),
                ('bank', models.CharField(choices=[('NB', 'Não é um banco'), ('BB', 'Banco do Basil'), ('IT', 'Itaú'), ('CX', 'Caixa'), ('BD', 'Bradesco'), ('ST', 'Santander'), ('C6', 'C6 Bank'), ('BP', 'BTG Pactual'), ('NU', 'Nubank'), ('IN', 'Inter')], default='NAB', max_length=14)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('count', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counts.savings', verbose_name='Saving person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saving',
                'verbose_name_plural': 'Savings',
            },
        ),
        migrations.CreateModel(
            name='Legal_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='')),
                ('bank', models.CharField(choices=[('NB', 'Não é um banco'), ('BB', 'Banco do Basil'), ('IT', 'Itaú'), ('CX', 'Caixa'), ('BD', 'Bradesco'), ('ST', 'Santander'), ('C6', 'C6 Bank'), ('BP', 'BTG Pactual'), ('NU', 'Nubank'), ('IN', 'Inter')], default='NAB', max_length=14)),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('indentification', models.CharField(max_length=14, verbose_name='Indentification')),
                ('count', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counts.legal', verbose_name='Juridical person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Juridical',
                'verbose_name_plural': 'Juridicals',
            },
        ),
        migrations.CreateModel(
            name='Checking_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='')),
                ('bank', models.CharField(choices=[('NB', 'Não é um banco'), ('BB', 'Banco do Basil'), ('IT', 'Itaú'), ('CX', 'Caixa'), ('BD', 'Bradesco'), ('ST', 'Santander'), ('C6', 'C6 Bank'), ('BP', 'BTG Pactual'), ('NU', 'Nubank'), ('IN', 'Inter')], default='NAB', max_length=14)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('count', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counts.checking', verbose_name='Checking Person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Physique',
                'verbose_name_plural': 'Physiques',
            },
        ),
    ]
