# Generated by Django 3.2.8 on 2021-11-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking_person',
            name='count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counts.checking', verbose_name='Checking count'),
        ),
        migrations.AlterField(
            model_name='checking_person',
            name='date',
            field=models.DateField(verbose_name='Date create/Bday'),
        ),
        migrations.AlterField(
            model_name='legal_person',
            name='count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counts.legal', verbose_name='Juridical count'),
        ),
        migrations.AlterField(
            model_name='legal_person',
            name='date',
            field=models.DateField(verbose_name='Date create/Bday'),
        ),
        migrations.AlterField(
            model_name='savings_person',
            name='count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counts.savings', verbose_name='Saving count'),
        ),
        migrations.AlterField(
            model_name='savings_person',
            name='date',
            field=models.DateField(verbose_name='Date create/Bday'),
        ),
    ]
