# Generated by Django 3.2.8 on 2021-11-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=6, verbose_name='Agency')),
                ('count', models.CharField(max_length=7, verbose_name='Count')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Balance')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limit')),
            ],
            options={
                'verbose_name': 'Checking',
                'verbose_name_plural': 'Checkings',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=6, verbose_name='Agency')),
                ('count', models.CharField(max_length=7, verbose_name='Count')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Balance')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limit')),
            ],
            options={
                'verbose_name': 'Juridical',
                'verbose_name_plural': 'Juridicals',
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=6, verbose_name='Agency')),
                ('count', models.CharField(max_length=7, verbose_name='Count')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Saving',
                'verbose_name_plural': 'Savings',
            },
        ),
    ]
